accounts:
  - name: alice
    coins: ["20000ufetf", "200000000stake"]
  - name: bob
    coins: ["10000ufetf", "100000000stake"]
  - name: faucet
    coins: ["50000000000000ufetf", "100000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: faucet
  coins: ["50000000000000ufetf", "100000stake"]
